/* ============================================================================
 *  URL → invitation config.  No backend: every guest variant is encoded in the
 *  query string, generated by the host control panel.
 *
 *  Params:
 *    side      bride | groom | joint        (hosting voice + default functions)
 *    fns       csv of event ids             (which functions to show)
 *    preset    all | wedding | shagun-wedding | bride | groom
 *    to        guest name (personalised greeting)
 *    countdown/venue/rsvp = 0               (hide that section)
 *    host                                   (presence opens control panel)
 *
 *  A bare URL with no params = the full joint invitation, everything on.
 *
 *  Opaque variant links: the same query string, base64url-encoded into the
 *  path (/{slug}). parseInvitation decodes the slug first, then overlays any
 *  explicit query params — so /{slug}?host opens the builder on that variant.
 * ========================================================================== */
import { couple, events, presets } from '../data.js';

const EVENT_IDS = events.map((e) => e.id);
const SIDES = ['bride', 'groom', 'joint'];
export const SECTION_IDS = ['countdown', 'venue', 'rsvp'];

function sideDefaultIds(side) {
  if (side === 'bride') return presets.bride.ids;
  if (side === 'groom') return presets.groom.ids;
  return presets.all.ids; // joint → everything
}

/** Keep only known ids, preserve canonical chronological order. */
function sanitiseIds(ids) {
  const set = new Set(ids);
  return EVENT_IDS.filter((id) => set.has(id));
}

/** Couple names in hosting-side order: bride variants put the bride first. */
export function orderedCouple(side) {
  return side === 'bride' ? [couple.bride, couple.groom] : [couple.groom, couple.bride];
}

/** base64url-encode a control-panel state into an opaque link slug. */
export function encodeSlug(state) {
  const q = buildQuery(state).replace(/^\?/, '');
  return btoa(q).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** Decode a path slug back to a query string. Unknown junk → '' (default invite). */
export function decodeSlug(slug) {
  try {
    return atob(slug.replace(/-/g, '+').replace(/_/g, '/'));
  } catch {
    return '';
  }
}

export function parseInvitation(search = '', pathname = '') {
  // path slug first, explicit query params override it
  const slug = pathname.replace(/^\/+|\/+$/g, '');
  const p = new URLSearchParams(slug ? decodeSlug(slug) : '');
  for (const [k, v] of new URLSearchParams(search)) p.set(k, v);

  const side = SIDES.includes(p.get('side')) ? p.get('side') : 'joint';

  // function selection: preset > fns > side default
  let ids;
  const presetKey = p.get('preset');
  if (presetKey && presets[presetKey]) {
    ids = presets[presetKey].ids;
  } else if (p.has('fns')) {
    ids = (p.get('fns') || '').split(',').map((s) => s.trim());
  } else {
    ids = sideDefaultIds(side);
  }
  const eventIds = sanitiseIds(ids);

  const sections = {
    countdown: p.get('countdown') !== '0',
    venue: p.get('venue') !== '0',
    rsvp: p.get('rsvp') !== '0',
  };

  return {
    side,
    eventIds,
    sections,
    guestName: (p.get('to') || '').trim(),
    isHost: p.has('host'),
  };
}

/** Ordered, hydrated event objects for the current selection. */
export function selectedEvents(eventIds) {
  const set = new Set(eventIds);
  return events
    .filter((e) => set.has(e.id))
    .sort((a, b) => a.order - b.order);
}

/** Build a query string from a control-panel state object. */
export function buildQuery(state) {
  const p = new URLSearchParams();
  if (state.side && state.side !== 'joint') p.set('side', state.side);
  if (state.guestName) p.set('to', state.guestName);

  // store the function selection compactly: a matching preset name if possible,
  // otherwise the explicit id list.
  const sel = sanitiseIds(state.eventIds || []);
  const presetMatch = Object.entries(presets).find(
    ([, v]) => v.ids.length === sel.length && v.ids.every((id) => sel.includes(id))
  );
  if (presetMatch && presetMatch[0] === 'all') {
    /* default — omit for a clean link */
  } else if (presetMatch) {
    p.set('preset', presetMatch[0]);
  } else {
    p.set('fns', sel.join(','));
  }

  for (const id of SECTION_IDS) {
    if (state.sections && state.sections[id] === false) p.set(id, '0');
  }

  const qs = p.toString();
  return qs ? `?${qs}` : '';
}

/** Absolute shareable URL for a guest — an opaque /{slug} link. */
export function buildShareUrl(baseUrl, state) {
  const base = (baseUrl || '').replace(/[?#].*$/, '').replace(/\/$/, '');
  return `${base}/${encodeSlug(state)}`;
}

/** wa.me link to forward the invitation to a guest. */
export function buildWhatsAppShare(url, guestName, coupleNames) {
  const greeting = guestName ? `Dear ${guestName},\n\n` : '';
  const msg =
    `${greeting}With great joy, you are invited to the wedding celebrations of ` +
    `${coupleNames}. 💐\n\nOpen your invitation here:\n${url}`;
  return `https://wa.me/?text=${encodeURIComponent(msg)}`;
}

/** wa.me link that delivers a completed RSVP to the hosts. */
export function buildRsvpWhatsApp(number, answers) {
  const lines = [
    '🎉 *RSVP — Wedding*',
    `Name: ${answers.name || '—'}`,
    `Phone: ${answers.phone || '—'}`,
    `Guests: ${answers.party || '1'}`,
    `Arrival: ${answers.arrival || '—'}`,
  ];
  const text = encodeURIComponent(lines.join('\n'));
  return `https://wa.me/${number}?text=${text}`;
}
