/* ============================================================================
 *  URL → invitation config.  No backend: every guest variant is encoded in the
 *  query string, generated by the host control panel.
 *
 *  Params:
 *    side      bride | groom | joint        (hosting voice + default functions)
 *    fns       csv of event ids             (which functions to show)
 *    preset    all | wedding | shagun-wedding | bride | groom
 *    to        guest name (personalised greeting)
 *    countdown/story/venue/rsvp = 0         (hide that section)
 *    music     = 0                          (disable background music)
 *    host                                   (presence opens control panel)
 *
 *  A bare URL with no params = the full joint invitation, everything on.
 * ========================================================================== */
import { events, presets } from '../data.js';

const EVENT_IDS = events.map((e) => e.id);
const SIDES = ['bride', 'groom', 'joint'];
export const SECTION_IDS = ['countdown', 'story', 'venue', 'rsvp'];

function sideDefaultIds(side) {
  if (side === 'bride') return presets.bride.ids;
  if (side === 'groom') return presets.groom.ids;
  return presets.all.ids; // joint → everything
}

/** Keep only known ids, preserve canonical chronological order. */
function sanitiseIds(ids) {
  const set = new Set(ids);
  return EVENT_IDS.filter((id) => set.has(id));
}

export function parseInvitation(search = '') {
  const p = new URLSearchParams(search);

  const side = SIDES.includes(p.get('side')) ? p.get('side') : 'joint';

  // function selection: preset > fns > side default
  let ids;
  const presetKey = p.get('preset');
  if (presetKey && presets[presetKey]) {
    ids = presets[presetKey].ids;
  } else if (p.has('fns')) {
    ids = (p.get('fns') || '').split(',').map((s) => s.trim());
  } else {
    ids = sideDefaultIds(side);
  }
  const eventIds = sanitiseIds(ids);

  const sections = {
    events: eventIds.length > 0,
    countdown: p.get('countdown') !== '0',
    story: p.get('story') !== '0',
    venue: p.get('venue') !== '0',
    rsvp: p.get('rsvp') !== '0',
  };

  return {
    side,
    eventIds,
    sections,
    music: p.get('music') !== '0',
    guestName: (p.get('to') || '').trim(),
    isHost: p.has('host'),
  };
}

/** Ordered, hydrated event objects for the current selection. */
export function selectedEvents(eventIds) {
  const set = new Set(eventIds);
  return events
    .filter((e) => set.has(e.id))
    .sort((a, b) => a.order - b.order);
}

/** Build a query string from a control-panel state object. */
export function buildQuery(state) {
  const p = new URLSearchParams();
  if (state.side && state.side !== 'joint') p.set('side', state.side);
  if (state.guestName) p.set('to', state.guestName);

  // store the function selection compactly: a matching preset name if possible,
  // otherwise the explicit id list.
  const sel = sanitiseIds(state.eventIds || []);
  const presetMatch = Object.entries(presets).find(
    ([, v]) => v.ids.length === sel.length && v.ids.every((id) => sel.includes(id))
  );
  if (presetMatch && presetMatch[0] === 'all') {
    /* default — omit for a clean link */
  } else if (presetMatch) {
    p.set('preset', presetMatch[0]);
  } else {
    p.set('fns', sel.join(','));
  }

  for (const id of SECTION_IDS) {
    if (state.sections && state.sections[id] === false) p.set(id, '0');
  }
  if (state.music === false) p.set('music', '0');

  const qs = p.toString();
  return qs ? `?${qs}` : '';
}

/** Absolute shareable URL for a guest. */
export function buildShareUrl(baseUrl, state) {
  const base = (baseUrl || '').replace(/[?#].*$/, '').replace(/\/$/, '');
  return `${base}/${buildQuery(state)}`.replace(/\/\?/, '/?').replace(/\/$/, '/');
}

/** wa.me link to forward the invitation to a guest. */
export function buildWhatsAppShare(url, guestName, coupleNames) {
  const greeting = guestName ? `Dear ${guestName},\n\n` : '';
  const msg =
    `${greeting}With great joy, you are invited to the wedding celebrations of ` +
    `${coupleNames}. 💐\n\nOpen your invitation here:\n${url}`;
  return `https://wa.me/?text=${encodeURIComponent(msg)}`;
}

/** wa.me link that delivers a completed RSVP to the hosts. */
export function buildRsvpWhatsApp(number, answers) {
  const lines = [
    '🎉 *RSVP — Wedding*',
    `Name: ${answers.name || '—'}`,
    `Phone: ${answers.phone || '—'}`,
    `Guests: ${answers.party || '1'}`,
    `Food: ${answers.food || '—'}`,
  ];
  if (answers.song) lines.push(`Song request: ${answers.song}`);
  if (answers.message) lines.push(`Message: ${answers.message}`);
  const text = encodeURIComponent(lines.join('\n'));
  return `https://wa.me/${number}?text=${text}`;
}
